### PR TITLE
Add projectid label/omit default module label

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
If we are doing this, we should also add the minorversion, module and version labels for AppEngine apps.

**Comment by ofrobots** [comment]
My bad, we already had those.

I think the object layout for layouts might be different from what the API expects. I think the `labels` property is expected to be an array of objects of type `{key: 'something', value: 'something'}`.

**Comment by matthewloring** [comment]
@ofrobots I think the format has been clarified.

**Comment by ofrobots** [comment]
LGTM if the e2e tests pass.

**Comment by matthewloring** [comment]
They do.

**Pull request merged**
