### PR TITLE
fix: update to the latest @google-cloud/common

### PR DESCRIPTION
**Pull request by JustinBeckwith**
This is at least compiling, but the tests are failing.  I'm not familiar enough with what's going on with the internals to effectively debug.  If someone can take this PR over... great!  If not, feel free to discard :)

Fixes: #433

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
@DominicKramer I did a lot of the grunt work here getting things to compile.  Any chance I could trouble you to bring this home?

**Comment by DominicKramer** [comment]
@JustinBeckwith Thanks for working on the compiling issues.  I can take over this PR to get the tests passing.

**Comment by ofrobots** [comment]
@DominicKramer this is a duplicate of #473. Which one would you like to be closed. Are you still on top of this one?

**Comment by DominicKramer** [comment]
@ofrobots I will continue with this PR.  I closed #473.

**Comment by ofrobots** [comment]
This is blocking #383.

**Comment by DominicKramer** [comment]
Closed in favor of PR #481.

**Pull request closed without merging**
