### PR TITLE
fix(package): update gcp-metadata to version 0.6.1

### PR DESCRIPTION
**Pull request by ofrobots**
Closes #397

### CODE REVIEW

**Comment by ofrobots** [comment]
It's all good @googlebot.

**Comment by ofrobots** [comment]
The tests are failing. This will need to be looked at. I'll do so when I get a chance, but others are welcome to look too in the meanwhile.

**Comment by jinwoo** [comment]
/cc @JustinBeckwith 

The failures are from `tsc`.

I think it's because `gcp-metadata` recently upgraded to `tsc` 2.7.0 and started to use the "Constant named properties" feature that was added to 2.7.0: http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#constant-named-properties.

See the recent change that introduced it: https://github.com/stephenplusplus/gcp-metadata/commit/0b6eb38466ab9b9588dc6101fb9a4b736abe903a#diff-f41e9d04a45c83f3b6f6e630f10117feR10

**Comment by JustinBeckwith** [comment]
Yeah, I was kinda excited about that feature :)  Is it ok if we just upgrade this lib to TypeScript 2.7?

**Comment by jinwoo** [comment]
I think we should upgrade all our repos to TS 2.7 anyway. As a related note, I'd love `gts` to be upgraded to TS 2.7 and to support `--esModuleInterop`. For that, we need to merge https://github.com/google/ts-style/pull/125 into the master branch.

**Comment by DominicKramer** [comment]
Closing since this has been replaced by PR #407.

**Pull request closed without merging**
