### PR TITLE
Improve coverage reporting

### PR DESCRIPTION
**Pull request by matthewloring**

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL

**Comment by ofrobots** [comment]
Do you know what this seems to decrease coverage?

**Comment by ofrobots** [comment]
LGTM once we understand what is going on with coveralls.

**Comment by matthewloring** [comment]
The old coverage runs never loaded `debuglet.js`. Coverage now also runs the standalone tests which adds a new file with 44% coverage decreasing the overall percentage.

**Pull request merged**
