### PR TITLE
Switch from findit to findit2

### PR DESCRIPTION
**Pull request by ofrobots**
https://www.npmjs.com/package/findit2 seems to fix a few open bugs with
findit, which doesn't seem to be maintained anymore. Furthermore, this
fixes the issue that findit was intermittently failing to find all the
files on windows causing the AppVeyor builds to fail.

### CODE REVIEW

**Comment by ofrobots** [comment]
PTAL. AppVeyor is green again!

**Comment by ofrobots** [comment]
`walker` is indeed more popular – in fact I compared the output from `findit` to `walker` to test if `findit` was buggy. 

However, `findit2` has a compatible API to `findit` and was a minimal change to our codebase.

**Comment by matthewloring** [comment]
Yup, sounds good!

**Comment by DominicKramer** [comment]
I second using `findit2` for the above mentioned minimal changes to our codebase.

**Pull request merged**
